#!/bin/bash

case $1 in
    on)
        xrandr --output eDP1 --auto --primary --output HDMI2 --auto --right-of eDP1 2>&1 | tee -a $HOME/.xrandr.log
        ;;
    off)
        xrandr --auto 2>&1 | tee -a $HOME/.xrandr.log
        ;;
    *)
        echo "Use 'on' or 'off'"
        ;;
esac
